export interface SEOToolData {
  slug: string;
  toolId: string; // maps to tools[] id in tools.ts
  title: string;
  h1: string;
  metaDescription: string;
  keywords: string[];
  whyUse: string;
  howTo: { step: string; description: string }[];
  faqs: { question: string; answer: string }[];
  relatedSlugs: string[];
  aiRelatedSlugs: string[];
}

export const seoTools: SEOToolData[] = [
  {
    slug: "merge-pdf",
    toolId: "merge",
    title: "Merge PDF Online Free – Fast & Secure | PDFShop",
    h1: "Merge PDF Files Online",
    metaDescription: "Use PDFShop to merge multiple PDF files into one document online for free. Fast, secure and easy-to-use PDF merger with drag & drop.",
    keywords: ["merge pdf", "combine pdf", "pdf merger online", "join pdf files", "merge pdf free", "combine pdf online"],
    whyUse: "Merging PDFs online saves time and eliminates the need for desktop software. PDFShop lets you combine multiple documents into a single PDF in seconds, preserving formatting and quality. Perfect for reports, contracts, and presentations.",
    howTo: [
      { step: "Upload PDFs", description: "Drag & drop or click to upload the PDF files you want to merge." },
      { step: "Arrange Order", description: "Reorder your files by dragging them into the desired sequence." },
      { step: "Merge & Download", description: "Click merge and download your combined PDF instantly." },
    ],
    faqs: [
      { question: "Is merging PDFs free?", answer: "Yes, PDFShop offers free PDF merging with no watermarks for basic usage." },
      { question: "Is it safe to merge PDFs online?", answer: "Absolutely. Your files are processed securely and automatically deleted after processing." },
      { question: "How many PDFs can I merge at once?", answer: "You can merge up to 20 PDF files at once with the free plan, and unlimited with premium." },
      { question: "Will merging change my PDF quality?", answer: "No, PDFShop preserves the original quality of all merged documents." },
    ],
    relatedSlugs: ["split-pdf", "compress-pdf", "reorder-pages", "remove-pages", "extract-pages"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "split-pdf",
    toolId: "split",
    title: "Split PDF Online Free – Extract Pages Easily | PDFShop",
    h1: "Split PDF Pages Online",
    metaDescription: "Use PDFShop to split PDF files into separate pages or sections online for free. Fast, secure and easy-to-use PDF splitter.",
    keywords: ["split pdf", "separate pdf pages", "pdf splitter online", "extract pdf pages", "divide pdf", "split pdf free"],
    whyUse: "Splitting PDFs online lets you extract specific pages or break large documents into smaller files. PDFShop makes it simple to separate chapters, remove unwanted pages, or create custom document sections.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF file you want to split." },
      { step: "Select Pages", description: "Choose which pages to extract or set split ranges." },
      { step: "Split & Download", description: "Click split and download your separated PDF files." },
    ],
    faqs: [
      { question: "Can I split a PDF into individual pages?", answer: "Yes, PDFShop can split any PDF into individual single-page files." },
      { question: "Is splitting PDFs free?", answer: "Yes, basic PDF splitting is completely free on PDFShop." },
      { question: "Can I select specific page ranges?", answer: "Absolutely. You can specify exact page ranges like 1-3, 5, 7-10." },
      { question: "How long does splitting take?", answer: "Splitting is nearly instant, usually taking less than 2 seconds." },
    ],
    relatedSlugs: ["merge-pdf", "extract-pages", "remove-pages", "reorder-pages", "compress-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "compress-pdf",
    toolId: "compress",
    title: "Compress PDF Online Free – Reduce File Size | PDFShop",
    h1: "Compress PDF Files Online",
    metaDescription: "Use PDFShop to compress PDF files and reduce file size online for free. Maintain quality while shrinking your documents.",
    keywords: ["compress pdf", "reduce pdf size", "pdf compressor online", "shrink pdf", "optimize pdf", "compress pdf free"],
    whyUse: "Large PDF files are hard to email and slow to load. PDFShop's compressor reduces file size while maintaining visual quality, making your documents perfect for sharing via email, uploading to websites, or archiving.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF file you want to compress." },
      { step: "Choose Quality", description: "Select your preferred compression level." },
      { step: "Compress & Download", description: "Click compress and download your smaller PDF file." },
    ],
    faqs: [
      { question: "How much can PDFs be compressed?", answer: "Typically 40-80% size reduction depending on content type and compression level." },
      { question: "Will compression reduce quality?", answer: "PDFShop offers balanced compression that maintains readability while reducing size significantly." },
      { question: "Is PDF compression free?", answer: "Yes, basic compression is free. Premium offers advanced compression options." },
      { question: "Can I compress multiple PDFs?", answer: "Yes, you can compress multiple files. Premium users get batch processing." },
    ],
    relatedSlugs: ["merge-pdf", "split-pdf", "repair-pdf", "convert-pdfa", "rotate-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "ai-insights"],
  },
  {
    slug: "pdf-to-word",
    toolId: "pdf-to-word",
    title: "PDF to Word Converter Free – Convert Online | PDFShop",
    h1: "Convert PDF to Word Online",
    metaDescription: "Use PDFShop to convert PDF files to editable Word documents online for free. Preserve formatting and layout perfectly.",
    keywords: ["pdf to word", "convert pdf to docx", "pdf to word converter", "pdf to doc online", "pdf to word free"],
    whyUse: "Converting PDFs to Word documents makes them editable and easy to modify. PDFShop preserves your original formatting, tables, and images while creating a fully editable DOCX file.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF file you want to convert to Word." },
      { step: "Convert", description: "PDFShop automatically converts your PDF preserving layout." },
      { step: "Download Word File", description: "Download your editable Word document instantly." },
    ],
    faqs: [
      { question: "Is PDF to Word conversion accurate?", answer: "Yes, PDFShop preserves formatting, fonts, and layout during conversion." },
      { question: "Is the converter free?", answer: "Yes, basic PDF to Word conversion is free on PDFShop." },
      { question: "Can I convert scanned PDFs?", answer: "Scanned PDFs require OCR first. Use our OCR tool before converting." },
      { question: "What Word format is used?", answer: "PDFShop converts to .docx format, compatible with all modern Word processors." },
    ],
    relatedSlugs: ["pdf-to-excel", "pdf-to-ppt", "pdf-to-jpg", "word-to-pdf", "compress-pdf"],
    aiRelatedSlugs: ["translate-pdf", "ai-pdf-summary"],
  },
  {
    slug: "word-to-pdf",
    toolId: "word-to-pdf",
    title: "Word to PDF Converter Free – Convert Online | PDFShop",
    h1: "Convert Word to PDF Online",
    metaDescription: "Use PDFShop to convert Word documents to PDF online for free. Fast, secure conversion preserving all formatting.",
    keywords: ["word to pdf", "convert docx to pdf", "word to pdf converter", "doc to pdf online", "word to pdf free"],
    whyUse: "Converting Word to PDF ensures your document looks the same on every device. PDFShop creates professional PDFs from your Word files, preserving fonts, images, and layout perfectly.",
    howTo: [
      { step: "Upload Word File", description: "Upload your .docx or .doc file." },
      { step: "Convert", description: "PDFShop automatically converts your document to PDF." },
      { step: "Download PDF", description: "Download your converted PDF file instantly." },
    ],
    faqs: [
      { question: "Is Word to PDF conversion free?", answer: "Yes, PDFShop offers free Word to PDF conversion." },
      { question: "Will formatting be preserved?", answer: "Yes, all fonts, images, tables and layout are preserved in the PDF." },
      { question: "What file types are supported?", answer: "Both .doc and .docx Word formats are supported." },
      { question: "Is there a file size limit?", answer: "Free users can convert files up to 20MB. Premium has no limits." },
    ],
    relatedSlugs: ["excel-to-pdf", "ppt-to-pdf", "jpg-to-pdf", "pdf-to-word", "compress-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "jpg-to-pdf",
    toolId: "jpg-to-pdf",
    title: "JPG to PDF Converter Free – Images to PDF | PDFShop",
    h1: "Convert JPG to PDF Online",
    metaDescription: "Use PDFShop to convert JPG images to PDF documents online for free. Combine multiple images into one PDF easily.",
    keywords: ["jpg to pdf", "image to pdf", "convert jpg to pdf", "photo to pdf", "picture to pdf online", "jpg to pdf free"],
    whyUse: "Converting images to PDF creates professional documents from photos and scans. PDFShop lets you combine multiple JPG images into a single, organized PDF document perfect for sharing.",
    howTo: [
      { step: "Upload Images", description: "Upload JPG, PNG or other image files." },
      { step: "Arrange Order", description: "Drag to reorder images as needed." },
      { step: "Convert & Download", description: "Click convert and download your PDF." },
    ],
    faqs: [
      { question: "Can I convert multiple images to one PDF?", answer: "Yes, upload multiple images and PDFShop combines them into a single PDF." },
      { question: "What image formats are supported?", answer: "JPG, PNG, GIF, BMP, and WebP formats are all supported." },
      { question: "Is the conversion free?", answer: "Yes, basic image to PDF conversion is free." },
      { question: "Will image quality be preserved?", answer: "Yes, PDFShop maintains original image resolution in the PDF." },
    ],
    relatedSlugs: ["pdf-to-jpg", "scan-to-pdf", "merge-pdf", "compress-pdf", "word-to-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "ai-insights"],
  },
  {
    slug: "pdf-to-jpg",
    toolId: "pdf-to-jpg",
    title: "PDF to JPG Converter Free – Extract Images | PDFShop",
    h1: "Convert PDF to JPG Online",
    metaDescription: "Use PDFShop to convert PDF pages to JPG images online for free. Extract high-quality images from any PDF document.",
    keywords: ["pdf to jpg", "pdf to image", "convert pdf to jpg", "pdf to picture", "extract images from pdf", "pdf to jpg free"],
    whyUse: "Converting PDFs to images makes content easy to share on social media, embed in presentations, or use in documents. PDFShop extracts high-quality JPG images from every page of your PDF.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF you want to convert to images." },
      { step: "Select Pages", description: "Choose which pages to convert to JPG." },
      { step: "Download Images", description: "Download your JPG images as a zip file." },
    ],
    faqs: [
      { question: "What image quality can I expect?", answer: "PDFShop converts at high resolution (300 DPI) for crisp, clear images." },
      { question: "Can I convert specific pages only?", answer: "Yes, you can select individual pages or ranges to convert." },
      { question: "Is PDF to JPG free?", answer: "Yes, basic conversion is free on PDFShop." },
      { question: "What formats are available?", answer: "JPG and PNG formats are both available for download." },
    ],
    relatedSlugs: ["jpg-to-pdf", "pdf-to-word", "pdf-to-excel", "pdf-to-ppt", "compress-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "ai-insights"],
  },
  {
    slug: "ai-pdf-summary",
    toolId: "ai-summary",
    title: "AI PDF Summary Generator Free – Summarize PDFs | PDFShop",
    h1: "AI PDF Summary Generator",
    metaDescription: "Use PDFShop to generate AI-powered summaries of your PDF documents online for free. Get key points and insights instantly.",
    keywords: ["ai pdf summary", "summarize pdf", "pdf summary generator", "ai summarize document", "pdf key points", "auto summary pdf"],
    whyUse: "Reading lengthy PDFs takes time. PDFShop's AI summary extracts key points, main arguments, and essential information from any document in seconds, saving you hours of reading.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF document you want summarized." },
      { step: "AI Analyzes", description: "Our AI reads and understands your entire document." },
      { step: "Get Summary", description: "Receive a concise summary with key points highlighted." },
    ],
    faqs: [
      { question: "How accurate are AI summaries?", answer: "Our AI uses advanced language models to produce highly accurate, contextual summaries." },
      { question: "Is AI summary free?", answer: "Free users get 3 summaries per day. Premium users get unlimited access." },
      { question: "What languages are supported?", answer: "AI summary works with documents in English, Spanish, French, German, and many more languages." },
      { question: "How long can documents be?", answer: "Free users can summarize the first 2 pages. Premium supports full documents." },
    ],
    relatedSlugs: ["chat-with-pdf", "translate-pdf", "ai-insights", "compress-pdf", "merge-pdf"],
    aiRelatedSlugs: ["chat-with-pdf", "translate-pdf"],
  },
  {
    slug: "chat-with-pdf",
    toolId: "ai-chat",
    title: "Chat with PDF Online Free – AI PDF Chat | PDFShop",
    h1: "Chat with Your PDF Using AI",
    metaDescription: "Use PDFShop to chat with your PDF documents using AI. Ask questions and get instant answers from your files.",
    keywords: ["chat with pdf", "ai pdf chat", "ask pdf questions", "pdf chatbot", "talk to pdf", "pdf qa"],
    whyUse: "Instead of searching through pages, simply ask your PDF questions in natural language. PDFShop's AI reads your document and provides accurate answers with page references instantly.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF you want to chat with." },
      { step: "Ask Questions", description: "Type your questions in natural language." },
      { step: "Get Answers", description: "Receive accurate answers with citations from your document." },
    ],
    faqs: [
      { question: "How does PDF chat work?", answer: "Our AI reads your entire document and answers questions based on its content." },
      { question: "Is chat with PDF free?", answer: "Free users get 5 messages per day. Premium users get unlimited chat." },
      { question: "Can I ask complex questions?", answer: "Yes, the AI understands context and can answer multi-part questions." },
      { question: "Are my documents private?", answer: "Yes, your documents are processed securely and never shared." },
    ],
    relatedSlugs: ["ai-pdf-summary", "translate-pdf", "ai-insights", "merge-pdf", "compress-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "translate-pdf"],
  },
  {
    slug: "translate-pdf",
    toolId: "ai-translate",
    title: "Translate PDF Online Free – AI Translation | PDFShop",
    h1: "Translate PDF Documents Online",
    metaDescription: "Use PDFShop to translate PDF documents to any language online for free. AI-powered translation preserving formatting.",
    keywords: ["translate pdf", "pdf translator", "translate document online", "pdf translation free", "multilingual pdf"],
    whyUse: "Breaking language barriers is essential for global collaboration. PDFShop's AI translator converts your PDF content to any language while preserving the original formatting and layout.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF you want to translate." },
      { step: "Choose Language", description: "Select the target language for translation." },
      { step: "Translate & Download", description: "Get your translated PDF with preserved formatting." },
    ],
    faqs: [
      { question: "How many languages are supported?", answer: "PDFShop supports translation to over 50 languages including Spanish, French, German, Chinese, and more." },
      { question: "Is translation accurate?", answer: "Our AI provides professional-grade translations using advanced language models." },
      { question: "Is PDF translation free?", answer: "Free users can translate up to 2 pages. Premium unlocks full document translation." },
      { question: "Is formatting preserved?", answer: "Yes, the translated PDF maintains the original layout and formatting." },
    ],
    relatedSlugs: ["ai-pdf-summary", "chat-with-pdf", "ai-insights", "compress-pdf", "merge-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "rotate-pdf",
    toolId: "rotate",
    title: "Rotate PDF Online Free – Flip Pages Easily | PDFShop",
    h1: "Rotate PDF Pages Online",
    metaDescription: "Use PDFShop to rotate PDF pages online for free. Flip pages 90°, 180° or 270° with one click.",
    keywords: ["rotate pdf", "flip pdf pages", "pdf rotation online", "turn pdf pages", "rotate pdf free"],
    whyUse: "Scanned documents and photos often end up sideways or upside down. PDFShop lets you quickly rotate individual pages or entire documents to the correct orientation.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF with pages you want to rotate." },
      { step: "Select Rotation", description: "Choose rotation angle: 90°, 180°, or 270°." },
      { step: "Rotate & Download", description: "Apply rotation and download the corrected PDF." },
    ],
    faqs: [
      { question: "Can I rotate individual pages?", answer: "Yes, you can rotate specific pages or all pages at once." },
      { question: "Is PDF rotation free?", answer: "Yes, rotating PDFs is completely free on PDFShop." },
      { question: "What rotation angles are available?", answer: "You can rotate 90° clockwise, 90° counter-clockwise, or 180°." },
      { question: "Will rotation affect quality?", answer: "No, rotation preserves the original quality of your PDF." },
    ],
    relatedSlugs: ["crop-pdf", "merge-pdf", "split-pdf", "compress-pdf", "reorder-pages"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "watermark-pdf",
    toolId: "watermark",
    title: "Add Watermark to PDF Free – Stamp PDFs | PDFShop",
    h1: "Add Watermark to PDF Online",
    metaDescription: "Use PDFShop to add text or image watermarks to PDF files online for free. Protect your documents with custom stamps.",
    keywords: ["watermark pdf", "add watermark to pdf", "pdf stamp", "pdf watermark online", "stamp pdf free"],
    whyUse: "Watermarks protect your documents from unauthorized use and establish ownership. PDFShop lets you add custom text or image watermarks with full control over position, opacity, and style.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF you want to watermark." },
      { step: "Customize Watermark", description: "Enter text or upload an image for your watermark." },
      { step: "Apply & Download", description: "Apply the watermark and download your protected PDF." },
    ],
    faqs: [
      { question: "Can I add image watermarks?", answer: "Yes, both text and image watermarks are supported." },
      { question: "Is watermarking free?", answer: "Yes, basic watermarking is free on PDFShop." },
      { question: "Can I control watermark position?", answer: "Yes, you can adjust position, rotation, opacity, and size." },
      { question: "Will the watermark be permanent?", answer: "Yes, watermarks are embedded permanently in the PDF." },
    ],
    relatedSlugs: ["protect-pdf", "merge-pdf", "compress-pdf", "crop-pdf", "redact-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "protect-pdf",
    toolId: "protect",
    title: "Protect PDF with Password Free – Encrypt PDF | PDFShop",
    h1: "Protect PDF with Password",
    metaDescription: "Use PDFShop to add password protection to PDF files online for free. Encrypt and secure your sensitive documents.",
    keywords: ["protect pdf", "password protect pdf", "encrypt pdf", "secure pdf", "pdf password", "lock pdf"],
    whyUse: "Protecting PDFs with passwords prevents unauthorized access to sensitive information. PDFShop uses strong encryption to secure your documents, ideal for contracts, financial reports, and confidential files.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF you want to protect." },
      { step: "Set Password", description: "Enter a strong password for your PDF." },
      { step: "Encrypt & Download", description: "Download your password-protected PDF." },
    ],
    faqs: [
      { question: "What encryption is used?", answer: "PDFShop uses AES-256 encryption, the same standard used by banks." },
      { question: "Is PDF protection free?", answer: "Yes, basic password protection is free on PDFShop." },
      { question: "Can I set permissions too?", answer: "Yes, use our Advanced Permissions tool to restrict printing, copying, and editing." },
      { question: "Is my password stored?", answer: "No, your password is never stored on our servers." },
    ],
    relatedSlugs: ["unlock-pdf", "redact-pdf", "watermark-pdf", "permissions-pdf", "compress-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "unlock-pdf",
    toolId: "unlock",
    title: "Unlock PDF Online Free – Remove Password | PDFShop",
    h1: "Unlock PDF – Remove Password",
    metaDescription: "Use PDFShop to remove passwords from PDF files online for free. Unlock protected PDFs easily and securely.",
    keywords: ["unlock pdf", "remove pdf password", "pdf unlocker", "crack pdf password", "unlock pdf free"],
    whyUse: "Forgot your PDF password? PDFShop helps you remove password protection from your own documents so you can access, edit, and share them freely again.",
    howTo: [
      { step: "Upload PDF", description: "Upload the password-protected PDF." },
      { step: "Enter Password", description: "Enter the current password to verify ownership." },
      { step: "Unlock & Download", description: "Download your unlocked PDF without restrictions." },
    ],
    faqs: [
      { question: "Is unlocking PDFs legal?", answer: "Yes, unlocking your own PDFs is perfectly legal. We require you to know the password." },
      { question: "Is it free?", answer: "Yes, PDF unlocking is free on PDFShop." },
      { question: "Do I need the password?", answer: "Yes, you must know the current password to unlock the PDF." },
      { question: "Will the content be affected?", answer: "No, unlocking only removes the password; content remains unchanged." },
    ],
    relatedSlugs: ["protect-pdf", "redact-pdf", "watermark-pdf", "compress-pdf", "merge-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "crop-pdf",
    toolId: "crop",
    title: "Crop PDF Online Free – Trim Margins | PDFShop",
    h1: "Crop PDF Pages Online",
    metaDescription: "Use PDFShop to crop PDF pages and trim margins online for free. Remove unwanted whitespace from your documents.",
    keywords: ["crop pdf", "trim pdf margins", "pdf cropper online", "remove pdf margins", "resize pdf pages"],
    whyUse: "Cropping PDFs removes unwanted margins and whitespace, making documents look cleaner and more professional. Perfect for preparing presentations, printing, or creating uniform page sizes.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF you want to crop." },
      { step: "Set Margins", description: "Choose a preset or set custom crop margins." },
      { step: "Crop & Download", description: "Apply cropping and download your trimmed PDF." },
    ],
    faqs: [
      { question: "Can I crop specific pages?", answer: "Yes, you can crop individual pages or apply the same crop to all pages." },
      { question: "Is cropping free?", answer: "Yes, basic PDF cropping is free on PDFShop." },
      { question: "Will cropping reduce file size?", answer: "Cropping can slightly reduce file size by removing margin content." },
      { question: "Can I undo cropping?", answer: "Cropping is permanent in the output file, but your original file is never modified." },
    ],
    relatedSlugs: ["rotate-pdf", "compress-pdf", "watermark-pdf", "merge-pdf", "split-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "redact-pdf",
    toolId: "redact",
    title: "Redact PDF Online – Black Out Sensitive Info | PDFShop",
    h1: "Redact PDF Content Online",
    metaDescription: "Use PDFShop to permanently redact sensitive information from PDF files. Black out text, images and data securely.",
    keywords: ["redact pdf", "black out pdf", "censor pdf", "remove sensitive info pdf", "pdf redaction tool"],
    whyUse: "Redaction permanently removes sensitive information from PDFs, ensuring compliance with privacy regulations. PDFShop makes it easy to black out names, numbers, addresses, and other confidential data.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF containing sensitive information." },
      { step: "Select Areas", description: "Mark the areas you want to redact using presets or manual selection." },
      { step: "Redact & Download", description: "Apply redactions permanently and download the sanitized PDF." },
    ],
    faqs: [
      { question: "Is redaction permanent?", answer: "Yes, redacted content is permanently removed and cannot be recovered." },
      { question: "Is PDF redaction free?", answer: "Redaction is a premium feature for maximum security and compliance." },
      { question: "Can I redact images?", answer: "Yes, both text and image areas can be redacted." },
      { question: "Is this GDPR compliant?", answer: "Yes, our redaction permanently removes data, supporting GDPR compliance." },
    ],
    relatedSlugs: ["protect-pdf", "watermark-pdf", "permissions-pdf", "compress-pdf", "merge-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "ai-insights"],
  },
  {
    slug: "repair-pdf",
    toolId: "repair",
    title: "Repair PDF Online Free – Fix Corrupted Files | PDFShop",
    h1: "Repair Corrupted PDF Files",
    metaDescription: "Use PDFShop to repair corrupted or damaged PDF files online for free. Recover content from broken PDF documents.",
    keywords: ["repair pdf", "fix corrupted pdf", "pdf recovery", "broken pdf fix", "damaged pdf repair"],
    whyUse: "Corrupted PDFs can mean lost documents and wasted work. PDFShop's repair tool uses multiple recovery strategies to salvage content from damaged files, saving your important documents.",
    howTo: [
      { step: "Upload PDF", description: "Upload the corrupted or damaged PDF file." },
      { step: "Auto Repair", description: "PDFShop automatically analyzes and repairs the file." },
      { step: "Download Fixed PDF", description: "Download your repaired PDF document." },
    ],
    faqs: [
      { question: "Can all corrupted PDFs be fixed?", answer: "Most corrupted PDFs can be repaired. Success depends on the level of corruption." },
      { question: "Is PDF repair free?", answer: "Yes, basic PDF repair is free on PDFShop." },
      { question: "Will I lose content?", answer: "PDFShop tries to recover all content, but severely damaged files may have some data loss." },
      { question: "How does repair work?", answer: "We use multiple recovery strategies including structure rebuild and content extraction." },
    ],
    relatedSlugs: ["compress-pdf", "convert-pdfa", "merge-pdf", "split-pdf", "protect-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "convert-pdfa",
    toolId: "convert-pdfa",
    title: "Convert to PDF/A Free – Archive Compliance | PDFShop",
    h1: "Convert PDF to PDF/A Format",
    metaDescription: "Use PDFShop to convert PDF files to PDF/A archival format online for free. Ensure long-term document preservation.",
    keywords: ["convert to pdfa", "pdf/a converter", "pdf archival format", "pdfa compliance", "long-term pdf storage"],
    whyUse: "PDF/A is the international standard for long-term document archiving. PDFShop converts your PDFs to PDF/A format, embedding fonts and metadata for guaranteed future accessibility.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF you want to convert to PDF/A." },
      { step: "Convert", description: "PDFShop adds compliance metadata and embeds fonts." },
      { step: "Download PDF/A", description: "Download your archive-compliant PDF/A file." },
    ],
    faqs: [
      { question: "What is PDF/A?", answer: "PDF/A is an ISO standard for long-term digital preservation of documents." },
      { question: "Is conversion free?", answer: "Yes, basic PDF/A conversion is free on PDFShop." },
      { question: "Which PDF/A version?", answer: "PDFShop converts to PDF/A-1b, the most widely supported version." },
      { question: "Why use PDF/A?", answer: "For archiving, legal compliance, and ensuring documents remain readable for decades." },
    ],
    relatedSlugs: ["compress-pdf", "repair-pdf", "protect-pdf", "merge-pdf", "watermark-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "ai-insights"],
  },
  {
    slug: "reorder-pages",
    toolId: "reorder-pages",
    title: "Reorder PDF Pages Free – Drag & Drop | PDFShop",
    h1: "Reorder PDF Pages Online",
    metaDescription: "Use PDFShop to reorder PDF pages with drag & drop online for free. Rearrange your document pages easily.",
    keywords: ["reorder pdf pages", "rearrange pdf", "sort pdf pages", "move pdf pages", "pdf page order"],
    whyUse: "Rearranging pages in a PDF doesn't require expensive software. PDFShop's drag-and-drop interface makes it simple to reorder pages visually, perfect for organizing reports and presentations.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF with pages you want to reorder." },
      { step: "Drag & Drop", description: "Drag pages to rearrange them in your preferred order." },
      { step: "Save & Download", description: "Save the new order and download your reorganized PDF." },
    ],
    faqs: [
      { question: "Is page reordering free?", answer: "Yes, reordering PDF pages is completely free." },
      { question: "Can I move multiple pages?", answer: "Yes, select and move multiple pages at once." },
      { question: "Will this affect content?", answer: "No, reordering only changes page sequence; content remains untouched." },
      { question: "How many pages can I reorder?", answer: "There's no page limit for reordering on PDFShop." },
    ],
    relatedSlugs: ["remove-pages", "extract-pages", "merge-pdf", "split-pdf", "rotate-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "remove-pages",
    toolId: "remove-pages",
    title: "Remove PDF Pages Free – Delete Pages | PDFShop",
    h1: "Remove Pages from PDF Online",
    metaDescription: "Use PDFShop to remove specific pages from PDF files online for free. Delete unwanted pages easily.",
    keywords: ["remove pdf pages", "delete pdf pages", "remove pages from pdf", "pdf page remover"],
    whyUse: "Removing unwanted pages from PDFs keeps your documents clean and focused. PDFShop makes it easy to select and delete specific pages without affecting the rest of your document.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF with pages you want to remove." },
      { step: "Select Pages", description: "Click on the pages you want to delete." },
      { step: "Remove & Download", description: "Remove selected pages and download the cleaned PDF." },
    ],
    faqs: [
      { question: "Is removing pages free?", answer: "Yes, removing PDF pages is completely free." },
      { question: "Can I remove multiple pages?", answer: "Yes, select as many pages as you want to remove." },
      { question: "Will this affect other pages?", answer: "No, only selected pages are removed; others remain unchanged." },
      { question: "Can I undo page removal?", answer: "The output is a new file; your original PDF is never modified." },
    ],
    relatedSlugs: ["extract-pages", "reorder-pages", "split-pdf", "merge-pdf", "compress-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "extract-pages",
    toolId: "extract-pages",
    title: "Extract PDF Pages Free – Pull Pages Out | PDFShop",
    h1: "Extract Pages from PDF Online",
    metaDescription: "Use PDFShop to extract specific pages from PDF files into a new document online for free.",
    keywords: ["extract pdf pages", "pull pages from pdf", "pdf page extractor", "copy pdf pages"],
    whyUse: "Extracting specific pages creates a new PDF with only the content you need. Perfect for pulling chapters from books, sections from reports, or specific forms from document packages.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF from which to extract pages." },
      { step: "Select Pages", description: "Choose which pages to extract." },
      { step: "Extract & Download", description: "Download a new PDF containing only selected pages." },
    ],
    faqs: [
      { question: "Is page extraction free?", answer: "Yes, extracting pages is completely free." },
      { question: "Can I extract non-consecutive pages?", answer: "Yes, select any combination of pages to extract." },
      { question: "Does this modify the original?", answer: "No, a new PDF is created; the original remains unchanged." },
      { question: "How many pages can I extract?", answer: "There's no limit on the number of pages you can extract." },
    ],
    relatedSlugs: ["remove-pages", "split-pdf", "merge-pdf", "reorder-pages", "compress-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "html-to-pdf",
    toolId: "html-to-pdf",
    title: "HTML to PDF Converter Free – Webpage to PDF | PDFShop",
    h1: "Convert HTML to PDF Online",
    metaDescription: "Use PDFShop to convert HTML content or webpages to PDF documents online for free. Preserve layout and styling.",
    keywords: ["html to pdf", "webpage to pdf", "convert html to pdf", "website to pdf", "html to pdf free"],
    whyUse: "Converting HTML to PDF lets you save web content as permanent, shareable documents. PDFShop renders your HTML with proper formatting, fonts, and layout into a professional PDF.",
    howTo: [
      { step: "Enter HTML/URL", description: "Paste your HTML code or enter a webpage URL." },
      { step: "Preview", description: "Preview how the PDF will look before converting." },
      { step: "Convert & Download", description: "Convert and download your PDF document." },
    ],
    faqs: [
      { question: "Is HTML to PDF free?", answer: "Yes, basic HTML to PDF conversion is free on PDFShop." },
      { question: "Are CSS styles preserved?", answer: "Yes, PDFShop renders HTML with full CSS support for accurate conversion." },
      { question: "Can I convert a live webpage?", answer: "Yes, enter a URL and PDFShop will convert the webpage to PDF." },
      { question: "What about images and fonts?", answer: "Images, fonts, and embedded media are all included in the PDF." },
    ],
    relatedSlugs: ["word-to-pdf", "jpg-to-pdf", "scan-to-pdf", "merge-pdf", "compress-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "scan-to-pdf",
    toolId: "scan-to-pdf",
    title: "Scan to PDF Free – Camera to PDF | PDFShop",
    h1: "Scan Documents to PDF",
    metaDescription: "Use PDFShop to scan documents using your camera and convert them to PDF online for free. Mobile-friendly scanner.",
    keywords: ["scan to pdf", "camera to pdf", "document scanner", "mobile pdf scanner", "scan document online"],
    whyUse: "Turn your phone or webcam into a document scanner. PDFShop captures images and converts them into clean, organized PDF documents — no scanner hardware needed.",
    howTo: [
      { step: "Capture Images", description: "Use your camera or upload scanned images." },
      { step: "Adjust & Rotate", description: "Rotate and arrange your scanned pages." },
      { step: "Create PDF", description: "Generate and download your scanned PDF document." },
    ],
    faqs: [
      { question: "Can I use my phone camera?", answer: "Yes, PDFShop works with any device camera for mobile scanning." },
      { question: "Is scanning free?", answer: "Yes, basic scan to PDF is free on PDFShop." },
      { question: "Can I scan multiple pages?", answer: "Yes, scan as many pages as needed into a single PDF." },
      { question: "Is OCR included?", answer: "For searchable text, use our separate OCR tool after scanning." },
    ],
    relatedSlugs: ["jpg-to-pdf", "ocr-pdf", "compress-pdf", "merge-pdf", "rotate-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "pdf-to-excel",
    toolId: "pdf-to-excel",
    title: "PDF to Excel Converter Free – Extract Tables | PDFShop",
    h1: "Convert PDF to Excel Online",
    metaDescription: "Use PDFShop to convert PDF tables to Excel spreadsheets online for free. Extract data accurately from PDF documents.",
    keywords: ["pdf to excel", "convert pdf to xlsx", "pdf table extractor", "pdf to spreadsheet", "pdf to excel free"],
    whyUse: "Extracting tables from PDFs into Excel makes data editable and analyzable. PDFShop accurately detects table structures and converts them to properly formatted spreadsheets.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF containing tables you want to extract." },
      { step: "Detect Tables", description: "PDFShop automatically detects and extracts table data." },
      { step: "Download Excel", description: "Download your formatted Excel spreadsheet." },
    ],
    faqs: [
      { question: "Are tables accurately extracted?", answer: "Yes, PDFShop uses advanced detection to preserve table structure and data." },
      { question: "Is conversion free?", answer: "Yes, basic PDF to Excel conversion is free." },
      { question: "What Excel format?", answer: "Files are converted to .xlsx format, compatible with Excel, Google Sheets, and more." },
      { question: "Can I convert multiple tables?", answer: "Yes, all tables in the PDF are extracted to separate sheets." },
    ],
    relatedSlugs: ["pdf-to-word", "pdf-to-ppt", "pdf-to-jpg", "excel-to-pdf", "compress-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "ai-insights"],
  },
  {
    slug: "pdf-to-ppt",
    toolId: "pdf-to-ppt",
    title: "PDF to PowerPoint Free – Convert to Slides | PDFShop",
    h1: "Convert PDF to PowerPoint Online",
    metaDescription: "Use PDFShop to convert PDF files to PowerPoint presentations online for free. Create editable slides from PDF documents.",
    keywords: ["pdf to ppt", "pdf to powerpoint", "convert pdf to pptx", "pdf to slides", "pdf to presentation"],
    whyUse: "Converting PDFs to PowerPoint creates editable presentations from your documents. PDFShop preserves layouts, images, and text formatting to create professional, ready-to-present slides.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF you want to convert to slides." },
      { step: "Convert", description: "PDFShop converts each page into an editable slide." },
      { step: "Download PPT", description: "Download your PowerPoint presentation." },
    ],
    faqs: [
      { question: "Are slides editable?", answer: "Yes, converted slides are fully editable in PowerPoint and Google Slides." },
      { question: "Is conversion free?", answer: "Yes, basic PDF to PowerPoint conversion is free." },
      { question: "What format is used?", answer: "Files are converted to .pptx format for maximum compatibility." },
      { question: "Are images preserved?", answer: "Yes, all images, charts, and graphics are preserved in the slides." },
    ],
    relatedSlugs: ["pdf-to-word", "pdf-to-excel", "pdf-to-jpg", "ppt-to-pdf", "compress-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "ai-insights"],
  },
  {
    slug: "excel-to-pdf",
    toolId: "excel-to-pdf",
    title: "Excel to PDF Converter Free – Spreadsheet to PDF | PDFShop",
    h1: "Convert Excel to PDF Online",
    metaDescription: "Use PDFShop to convert Excel spreadsheets to PDF documents online for free. Preserve formatting and formulas display.",
    keywords: ["excel to pdf", "convert xlsx to pdf", "spreadsheet to pdf", "excel to pdf free"],
    whyUse: "Converting Excel to PDF creates a fixed-layout document that looks the same everywhere. Perfect for sharing financial reports, data tables, and spreadsheets without worrying about formatting changes.",
    howTo: [
      { step: "Upload Excel", description: "Upload your .xlsx or .xls file." },
      { step: "Convert", description: "PDFShop converts your spreadsheet to PDF format." },
      { step: "Download PDF", description: "Download your formatted PDF document." },
    ],
    faqs: [
      { question: "Is formatting preserved?", answer: "Yes, cell formatting, colors, and borders are preserved in the PDF." },
      { question: "Is conversion free?", answer: "Yes, basic Excel to PDF conversion is free." },
      { question: "Are all sheets converted?", answer: "Yes, all sheets in the workbook are included in the PDF." },
      { question: "What file types are supported?", answer: "Both .xls and .xlsx formats are supported." },
    ],
    relatedSlugs: ["word-to-pdf", "ppt-to-pdf", "pdf-to-excel", "jpg-to-pdf", "compress-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "ppt-to-pdf",
    toolId: "ppt-to-pdf",
    title: "PPT to PDF Converter Free – Slides to PDF | PDFShop",
    h1: "Convert PowerPoint to PDF Online",
    metaDescription: "Use PDFShop to convert PowerPoint presentations to PDF online for free. Preserve slides, animations, and formatting.",
    keywords: ["ppt to pdf", "powerpoint to pdf", "convert pptx to pdf", "slides to pdf", "presentation to pdf"],
    whyUse: "Converting PowerPoint to PDF ensures your presentation looks perfect on any device. PDFShop preserves slide layouts, fonts, and images for professional PDF documents.",
    howTo: [
      { step: "Upload PPT", description: "Upload your .pptx or .ppt file." },
      { step: "Convert", description: "PDFShop converts your presentation to PDF." },
      { step: "Download PDF", description: "Download your formatted PDF document." },
    ],
    faqs: [
      { question: "Are animations preserved?", answer: "Animations are converted to static frames in the PDF." },
      { question: "Is conversion free?", answer: "Yes, basic PPT to PDF conversion is free." },
      { question: "Are speaker notes included?", answer: "Speaker notes can optionally be included in the PDF." },
      { question: "What formats are supported?", answer: "Both .ppt and .pptx formats are supported." },
    ],
    relatedSlugs: ["word-to-pdf", "excel-to-pdf", "pdf-to-ppt", "jpg-to-pdf", "compress-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "compare-pdf",
    toolId: "compare",
    title: "Compare PDF Files Free – Highlight Differences | PDFShop",
    h1: "Compare PDF Files Online",
    metaDescription: "Use PDFShop to compare two PDF files and highlight differences online for free. Find changes between document versions.",
    keywords: ["compare pdf", "pdf diff", "find differences in pdf", "compare documents", "pdf comparison tool"],
    whyUse: "Comparing PDFs helps you spot changes between document versions. PDFShop's word-level diff engine highlights additions, deletions, and modifications clearly, perfect for contract reviews and version control.",
    howTo: [
      { step: "Upload 2 PDFs", description: "Upload the original and modified PDF files." },
      { step: "Compare", description: "PDFShop analyzes both documents word by word." },
      { step: "View Differences", description: "See highlighted additions, deletions, and changes." },
    ],
    faqs: [
      { question: "How accurate is comparison?", answer: "PDFShop uses word-level diff for highly accurate change detection." },
      { question: "Is comparing free?", answer: "PDF comparison is a premium feature for advanced document management." },
      { question: "Can I compare different file types?", answer: "Currently, only PDF-to-PDF comparison is supported." },
      { question: "Are images compared?", answer: "Text content is compared; image comparison is coming soon." },
    ],
    relatedSlugs: ["merge-pdf", "split-pdf", "redact-pdf", "protect-pdf", "compress-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "ai-insights"],
  },
  {
    slug: "permissions-pdf",
    toolId: "permissions",
    title: "PDF Permissions Manager – Restrict Access | PDFShop",
    h1: "Set Advanced PDF Permissions",
    metaDescription: "Use PDFShop to set advanced permissions on PDF files. Restrict printing, copying, and editing for maximum security.",
    keywords: ["pdf permissions", "restrict pdf", "pdf access control", "prevent pdf copying", "pdf security settings"],
    whyUse: "Advanced permissions let you control exactly what recipients can do with your PDF. Restrict printing, copying text, and editing to protect sensitive documents and intellectual property.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF you want to restrict." },
      { step: "Set Permissions", description: "Choose which actions to allow or restrict." },
      { step: "Apply & Download", description: "Download your PDF with enforced permissions." },
    ],
    faqs: [
      { question: "What can I restrict?", answer: "You can restrict printing, copying text, editing, and form filling." },
      { question: "Is this feature free?", answer: "Advanced permissions is a premium feature for enhanced security." },
      { question: "Are restrictions enforceable?", answer: "Restrictions are enforced by PDF readers that comply with the PDF standard." },
      { question: "Can I set different levels?", answer: "Yes, you can mix and match permissions for fine-grained control." },
    ],
    relatedSlugs: ["protect-pdf", "redact-pdf", "watermark-pdf", "compress-pdf", "merge-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "ai-insights",
    toolId: "ai-insights",
    title: "AI PDF Insights Free – Extract Key Points | PDFShop",
    h1: "AI-Powered PDF Insights",
    metaDescription: "Use PDFShop to extract AI-powered insights, key points, and highlights from PDF documents online for free.",
    keywords: ["ai pdf insights", "extract key points", "pdf highlights", "ai document analysis", "pdf data extraction"],
    whyUse: "AI insights automatically extract the most important information from your documents — key points, statistics, dates, and actionable items — so you can quickly understand any document's essence.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF you want to analyze." },
      { step: "AI Analysis", description: "Our AI extracts key insights and highlights." },
      { step: "Review Results", description: "Browse organized insights, key points, and data." },
    ],
    faqs: [
      { question: "What insights are extracted?", answer: "Key points, statistics, dates, names, and actionable items." },
      { question: "Is it free?", answer: "Free users get 3 analyses per day. Premium unlocks unlimited usage." },
      { question: "How accurate are insights?", answer: "Our AI uses advanced models for highly accurate information extraction." },
      { question: "What document types work best?", answer: "Reports, research papers, contracts, and business documents produce the best results." },
    ],
    relatedSlugs: ["ai-pdf-summary", "chat-with-pdf", "translate-pdf", "compress-pdf", "merge-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "ocr-pdf",
    toolId: "ocr",
    title: "OCR PDF Online Free – Make PDFs Searchable | PDFShop",
    h1: "OCR PDF – Make Scanned PDFs Searchable",
    metaDescription: "Use PDFShop to make scanned PDF documents searchable with OCR online for free. Extract text from images and scans.",
    keywords: ["ocr pdf", "pdf ocr online", "searchable pdf", "text recognition pdf", "scan to text"],
    whyUse: "Scanned PDFs are just images — you can't search or copy text from them. PDFShop's OCR converts scanned documents into searchable, selectable text PDFs, making them fully functional.",
    howTo: [
      { step: "Upload PDF", description: "Upload your scanned or image-based PDF." },
      { step: "OCR Processing", description: "Our engine recognizes and extracts text from images." },
      { step: "Download Searchable PDF", description: "Download your searchable, text-enabled PDF." },
    ],
    faqs: [
      { question: "What is OCR?", answer: "OCR (Optical Character Recognition) converts images of text into actual searchable text." },
      { question: "Is OCR free?", answer: "Yes, basic OCR processing is free on PDFShop." },
      { question: "What languages are supported?", answer: "OCR supports English, Spanish, French, German, and many more languages." },
      { question: "How accurate is OCR?", answer: "Accuracy depends on scan quality, but typically achieves 95%+ for clear documents." },
    ],
    relatedSlugs: ["scan-to-pdf", "pdf-to-word", "compress-pdf", "merge-pdf", "ai-pdf-summary"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "page-numbers",
    toolId: "page-numbers",
    title: "Add Page Numbers to PDF Free | PDFShop",
    h1: "Add Page Numbers to PDF",
    metaDescription: "Use PDFShop to add page numbers to PDF documents online for free. Customize position, format, and style.",
    keywords: ["add page numbers pdf", "pdf page numbers", "number pdf pages", "pdf page numbering"],
    whyUse: "Page numbers make documents professional and easy to navigate. PDFShop lets you add customizable page numbers to any PDF with control over position, format, and starting number.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF you want to number." },
      { step: "Customize Style", description: "Choose position, format, and starting number." },
      { step: "Apply & Download", description: "Add page numbers and download your PDF." },
    ],
    faqs: [
      { question: "Can I customize position?", answer: "Yes, place numbers at top/bottom, left/center/right of each page." },
      { question: "Is this free?", answer: "Yes, adding page numbers is free on PDFShop." },
      { question: "Can I skip the first page?", answer: "Yes, you can set a starting page and skip title pages." },
      { question: "What formats are available?", answer: "Choose from numeric (1, 2, 3), Roman (I, II, III), or custom formats." },
    ],
    relatedSlugs: ["watermark-pdf", "merge-pdf", "reorder-pages", "compress-pdf", "rotate-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "edit-pdf",
    toolId: "edit-pdf",
    title: "Edit PDF Online Free – Modify Text & Images | PDFShop",
    h1: "Edit PDF Documents Online",
    metaDescription: "Use PDFShop to edit PDF text and images online for free. Modify, annotate, and update your PDF documents easily.",
    keywords: ["edit pdf", "modify pdf", "pdf editor online", "change pdf text", "edit pdf free"],
    whyUse: "Editing PDFs directly saves time compared to converting, editing, and re-converting. PDFShop lets you modify text, add annotations, and update images right in the browser.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF you want to edit." },
      { step: "Make Changes", description: "Edit text, add annotations, or modify images." },
      { step: "Save & Download", description: "Save your changes and download the edited PDF." },
    ],
    faqs: [
      { question: "Can I edit text directly?", answer: "Yes, click on text to edit it directly in the PDF." },
      { question: "Is PDF editing free?", answer: "Yes, basic editing features are free on PDFShop." },
      { question: "Can I add images?", answer: "Yes, you can add, resize, and position images in your PDF." },
      { question: "Are changes permanent?", answer: "Yes, changes are saved permanently in the downloaded PDF." },
    ],
    relatedSlugs: ["watermark-pdf", "sign-pdf", "crop-pdf", "merge-pdf", "compress-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "sign-pdf",
    toolId: "sign-pdf",
    title: "Sign PDF Online Free – Add Signature | PDFShop",
    h1: "Sign PDF Documents Online",
    metaDescription: "Use PDFShop to add your signature to PDF documents online for free. Draw, type, or upload your signature.",
    keywords: ["sign pdf", "add signature to pdf", "pdf signature", "e-sign pdf", "digital signature pdf"],
    whyUse: "Signing PDFs digitally eliminates printing, signing, and scanning. PDFShop lets you draw, type, or upload your signature and place it anywhere on your document.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF you want to sign." },
      { step: "Create Signature", description: "Draw, type, or upload your signature." },
      { step: "Place & Download", description: "Position your signature and download the signed PDF." },
    ],
    faqs: [
      { question: "Is e-signing legally valid?", answer: "Electronic signatures are legally valid in most countries under e-signature laws." },
      { question: "Is signing free?", answer: "Yes, basic PDF signing is free on PDFShop." },
      { question: "Can I save my signature?", answer: "Yes, save your signature for reuse on future documents." },
      { question: "Can multiple people sign?", answer: "Yes, you can add multiple signatures to the same document." },
    ],
    relatedSlugs: ["edit-pdf", "protect-pdf", "watermark-pdf", "merge-pdf", "compress-pdf"],
    aiRelatedSlugs: ["ai-pdf-summary", "chat-with-pdf"],
  },
  {
    slug: "ai-smart-search",
    toolId: "ai-search",
    title: "AI Smart Search in PDF Free | PDFShop",
    h1: "AI-Powered PDF Smart Search",
    metaDescription: "Use PDFShop to search through PDF documents with AI-powered smart search. Find information instantly with natural language.",
    keywords: ["ai pdf search", "smart search pdf", "find in pdf", "ai document search", "natural language pdf search"],
    whyUse: "Traditional search only finds exact matches. PDFShop's AI smart search understands context and meaning, so you can search using natural language and find relevant information even with different wording.",
    howTo: [
      { step: "Upload PDF", description: "Upload the PDF you want to search through." },
      { step: "Ask a Question", description: "Type your search query in natural language." },
      { step: "Get Results", description: "See highlighted relevant passages with page references." },
    ],
    faqs: [
      { question: "How is this different from Ctrl+F?", answer: "AI search understands meaning, not just exact text matches." },
      { question: "Is smart search free?", answer: "Free users get 5 searches per day. Premium unlocks unlimited." },
      { question: "What languages are supported?", answer: "AI search works with documents in multiple languages." },
      { question: "Can I search across multiple PDFs?", answer: "Currently, search works within a single uploaded PDF." },
    ],
    relatedSlugs: ["chat-with-pdf", "ai-pdf-summary", "ai-insights", "translate-pdf", "merge-pdf"],
    aiRelatedSlugs: ["chat-with-pdf", "ai-pdf-summary"],
  },
];

export const getSEOToolBySlug = (slug: string): SEOToolData | undefined =>
  seoTools.find((t) => t.slug === slug);

export const getAllSEOSlugs = (): string[] =>
  seoTools.map((t) => t.slug);

/** Map a tool ID to its SEO slug, if one exists */
export const getSEOSlugByToolId = (toolId: string): string | undefined => {
  const entry = seoTools.find((t) => t.toolId === toolId);
  return entry?.slug;
};
