project_id = "oblietbadczjdcslvskh"

[functions.ai-summary]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.ai-translate]
verify_jwt = false

[functions.ai-search]
verify_jwt = false

[functions.ai-insights]
verify_jwt = false

[functions.auto-generate-blogs]
verify_jwt = false
